name: unit-tests
run-name: ${{ github.actor }} is running the unit tests 🚀

on: [push]

jobs :
    unit-tests:
      name: Run unit tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
          #compile fat jar
        - name: Install JUnit and Hamcrest
          run: |
            curl -L -o junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
            curl -L -o hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

        - name: Compile
          run: cd scripts && make all

        - name: Run unit tests
          # run the tests and display the percentage of tests passed on a badge on the readme
          run: |
            cd scripts && make test > test-output.txt
            echo "##[set-output name=tests-passed;]$(cat test-output.txt | grep -oP 'Tests run: \K[0-9]+(?=,)' | head -1)"
            #upload test results
