name: unit-tests
run-name: ${{ github.actor }} is running the unit tests 🚀

on: [push]

jobs :
    unit-tests:
      name: Run unit tests
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'
        - run: java -cp | 
               lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar:build/classes/java/test org.junit.runner.JUnitCore |
               test
